name: feathers_client
description: Feathers client for Dart and Flutter.
version: 0.0.1
homepage: https://github.com/justraman/feathers
repository: https://github.com/justraman/feathers

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
